name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      
      - name: Check if Deno is installed
        run: deno --version

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
        
      - name: Check if pnpm is installed
        run: pnpm -v
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
        
      - name: Install dependencies
        working-directory: ./cyclades-server
        run: pnpm install

      - name: Build step
        run: "pnpm run build"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "cyclades-server"
          entrypoint: "server.ts"
          root: "./cyclades-server"
